name: flutter_posthog
description: Flutter implementation of Posthog Analytics for iOS, Android and Web
version: 1.9.0
homepage: https://www.posthog.com
repository: https://github.com/posthog/flutter-posthog
issue_tracker: https://github.com/posthog/flutter-posthog/issues
documentation: https://github.com/posthog/flutter-posthog#readme

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.posthog.flutter_posthog
        pluginClass: FlutterPosthogPlugin
      ios:
        pluginClass: FlutterPosthogPlugin
      web:
        pluginClass: PosthogWeb
        fileName: src/posthog_web.dart
